image: Visual Studio 2022

shallow_clone: true

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

services:
  - postgresql101

before_build:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - PATH=C:\Program Files\PostgreSQL\10\bin\;%PATH%
  - createdb rebus2_test
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build -c Release --no-restore

test_script:
  - dotnet test -c Release --no-restore
